{% set name = "python-libdiscid" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-libdiscid-{{ version }}.tar.gz
  sha256: f681053ebd7406dc7e11cf702afaa5a2d595a0db2de5a026c8c3fa5539eb5750

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=0.15
    - python
    - setuptools >=43
  # - pkgconfig Is only an optional dependancy and happens to make the build fail
    - pip
    - libdiscid
  run:
    - python

test:
  imports:
    - libdiscid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebastinas/python-libdiscid
  summary: Python bindings for libdiscid
  doc_url: https://pythonhosted.org/python-libdiscid/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
